# Generated by Django 2.1.2 on 2018-11-25 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TM', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'user profile', 'verbose_name_plural': 'user profile'},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
