# Generated by Django 2.1.2 on 2018-12-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TM', '0003_auto_20181125_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль пользователей', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterField(
            model_name='task',
            name='competition_date',
            field=models.DateTimeField(verbose_name='Срок выполнения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Задача'),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='Профиль',
        ),
    ]
