# Generated by Django 2.1.2 on 2018-12-05 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TM', '0005_auto_20181201_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='people',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
