# Generated by Django 2.1.2 on 2018-12-23 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TM', '0006_task_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='people',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
    ]
