# Generated by Django 2.1.2 on 2018-12-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TM', '0007_auto_20181223_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='people',
            new_name='executor',
        ),
    ]
