# Generated by Django 2.1.4 on 2018-12-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TM', '0008_auto_20181223_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
