# Generated by Django 2.1.4 on 2018-12-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TM', '0009_auto_20181225_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_image',
            field=models.ImageField(blank=True, default='task_images/task_default_image.png', null=True, upload_to='task_images/', verbose_name='Изображение'),
        ),
    ]
