# Generated by Django 2.1.4 on 2018-12-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TM', '0010_auto_20181225_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_image',
            field=models.ImageField(blank=True, default='/media/task_images/task_default_image.png', null=True, upload_to='task_images/', verbose_name='Изображение'),
        ),
    ]
