# Generated by Django 2.1.4 on 2018-12-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TM', '0013_auto_20181225_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_image',
            field=models.ImageField(blank=True, default='media/task_images/default_task_image.png', null=True, upload_to='task_images/', verbose_name='Изображение'),
        ),
    ]
