# Generated by Django 2.1.4 on 2018-12-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TM', '0014_auto_20181225_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_image',
            field=models.ImageField(blank=True, null=True, upload_to='task_images/', verbose_name='Изображение'),
        ),
    ]
