# Generated by Django 2.1.4 on 2018-12-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TM', '0017_auto_20181226_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='О себе'),
        ),
    ]
